services:
  backend:
    build: backend
    environment:
      - POSTGRES_DB=example
    secrets:
      - db-password
    depends_on:
      - db
    networks:
      - spring-postgres
    ports:
      - 80:8080
  frontend:
    build:
      context: frontend
    ports:
      - 81:80
    

  db:
    image: postgres:17
    restart: always
    env_file:
      - db/.env
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 3s
      retries: 5
      
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-postgres: 
    driver: bridge